### ISSUE TITLE
Unable to parse command line options: Missing argument for option: P

### ISSUE THREAD

**Issue by robmoore** [codegik/gitflow#1]
I'm running into an issue when trying to start a project. I run the target without specifying a profile and yet I'm getting the following error:

```
[INFO] Compiling project...
[INFO] mvn clean install -P 
    Unable to parse command line options: Missing argument for option: P
```

Looking at the source, it looks like the problem is in `AbstractGitFlowMojo`.

```
if (getSettings().getActiveProfiles() != null) {
   args.add("-P");
   args.add(StringUtils.join(getSettings().getActiveProfiles().iterator(), ","));
}
```

The project I'm trying to start a release on is a super POM project and it does have a profile defined with a number of submodules but this profile isn't an active profile (and there are no active profiles defined in the super POM).

**Comment by codegik** [comment]
Thanks for your collaboration. The bug was solved at the new version 1.2.11.
